remove the bash syntax highlighting
dagger/dagger pull request #1964
Opened 2022-03-31 13:57 UTC by dolanor

it was highlighting the wrong keywords (test, do)

2022-03-31 14:06 UTC, grouville approved these changes
LGTM, thanks 😇

2022-03-31 14:08 UTC, helderco requested changes
Please prepend "doc: " to the commit message so it doesn't get included in the changelog.

2022-03-31 14:08 UTC, helderco commented on docs/use-cases/1211-go-docker-swarm.md
> +```prose
I think "console" is better.

2022-03-31 14:16 UTC, dolanor commented on docs/use-cases/1211-go-docker-swarm.md
> +```prose
nice, didn't know about this one

2022-03-31 14:24 UTC, helderco approved these changes

2022-03-31 14:25 UTC, merged

2022-04-01 11:40 UTC, gerhard commented
> Please prepend "doc: " to the commit message so it doesn't get included in the changelog.

Just double-checking that the changelog release notes filtering is done on the commit messages, and not the PR titles (I assumed it was PR titles).

2022-04-01 12:34 UTC, helderco commented
It's commit messages.