ci: lint dagger using dagger
dagger/dagger pull request #2041
Opened 2022-04-05 01:22 UTC by aluzzardi

- `Makefile` now uses `dagger do lint` to lint
- GHA uses dagger to lint

2022-04-05 12:29 UTC, TomChv requested changes
LGTM, but I saw that CI has timeout, it's strange because we can see that operation are `CACHED`.

2022-04-05 12:29 UTC, TomChv commented on Makefile
> +cuefmt: dagger # Format all cue files
That command do not require dagger to works

2022-04-05 12:29 UTC, TomChv commented on .github/workflows/lint.yml
> +          DAGGER_CACHE_TO: "type=gha,mode=max,scope=dagger-ci-lint"
Why not `DAGGER_LOG_FORMAT: plain` here?

2022-04-05 19:26 UTC, aluzzardi commented
Thanks @TomChv 

I'm not 100% sure if the cache is working correctly, could you take a look?

2022-04-05 19:42 UTC, aluzzardi commented
@TomChv Ok here's my theory: As soon as we have a `#CacheDir`, since they're not persisted, it invalidates the cache resulting in a re-run.

Basically everything with a `#CacheDir` is executed every single time.

Is that a good assumption?

2022-04-06 18:25 UTC, aluzzardi commented
> I'm not sure because I could make cache works with go.#Build and it's using core.#CacheDir in go.#Container.

The `Dagger CI / Build` job here is using `go.#Build` and is not getting cached. I just re-triggered it 4 times.

2022-04-07 14:17 UTC, TomChv commented
> The Dagger CI / Build job here is using go.#Build and is not getting cached. I just re-triggered it 4 times.

Ok that's weird, in `Dagger CI / Build`, some action are cached but I see that the [huge one isn't](https://github.com/dagger/dagger/runs/5861154039?check_suite_focus=true#step:6:917).
Cache is definitely working but only in specific context. I must find what's going wrong with that.

2022-04-07 17:21 UTC, merged