feat: allow http modules
dagger/dagger pull request #2275
Opened 2022-04-22 17:22 UTC by jcdickinson

This allows `project update` to download .tar.gz modules from an HTTP server. The module name is derived from the host and path portions of the URL. The fragment portion of the URL is used to define the actual download path. For example, `https://github.com/dagger/dagger#/archive/refs/tags/v0.2.7.tar.gz` results in the `github.com/dagger/dagger` module name and `https://github.com/dagger/dagger/archive/refs/tags/v0.2.7.tar.gz` download URL.

Support for providing an authentication header has also been added. This is done with the `--authorization-header` flag. For example, `--authorization-header 'ghp_...'`.

Finally, some of the require_tests were broken. The tests seemed to represent desired behavior, so I updated`parseDaggerRepoName`.

Signed-off-by: Jonathan Dickinson

2022-04-22 17:49 UTC, jcdickinson commented
lint failure is due to Azure egress limit: https://github.com/dagger/dagger/runs/6132808931?check_suite_focus=true#step:6:384

```
5:43PM ERR actions.lint.cue._dag."1"._copy | failed: failed to compute cache key: failed to copy: invalid status response 503 Egress is over the account limit. for https://gel7acprodeus1file0.blob.core.windows.net/27543b5d759147d3b6e36a929aab1c78/fa1f96197eb4ec11997e281878563d51?sv=2019-07-07&sr=b&sig=gEI8KjkdxrSOaJqUvJZBsw02Equz4r1x%2BxaYdAJiG%2BY%3D&se=2022-04-22T18%3A43%3A43Z&sp=r&rscl=x-e2eid-98aca182-d5ab455b-aedf5d7e-57a9da85
```

2022-04-22 20:47 UTC, jcdickinson commented
Another option here might be to detect `github.com` and build a download URL, if a PAT is provided.

2022-04-27 13:54 UTC, ab-passos requested changes

2022-04-27 13:54 UTC, ab-passos commented on mod/http_repo_test.go
> +	for _, c := range cases {
Wouldn't it be better to use https://pkg.go.dev/net/http/httptest and make this a unit test?

2022-04-27 13:54 UTC, ab-passos commented on mod/require.go
> +	clone, _ := url.Parse(repoName)
isn't it repeated with line above?

2022-04-28 20:07 UTC, jcdickinson commented
@TomChv all things considered, I'm increasingly disliking my approach with this PR. I think that https://github.com/dagger/dagger/pull/2286 is a much better approach.

2022-05-13 14:29 UTC, closed without merging