docs(faq): explain field shadowing
dagger/dagger pull request #2544
Opened 2022-06-01 10:19 UTC by TomChv

Resolves: #2231

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

2022-06-01 21:05 UTC, samalba requested changes
Overall the content is useful as a FAQ article.

If we merge it to a guide ("coding style"), it could be summarized in fewer words. Basically explaining that key names need to be escaped with double quotes (`"keyName"`) if there is another key with the same name somewhere in the same scope, otherwise it'll be considered as a reference and produce a CUE error.

2022-06-01 21:05 UTC, samalba commented on docs/faq/1241-field-shadowing.md
> +# Understand field shadowing and how to avoid it
Understanding

2022-06-02 13:30 UTC, TomChv commented
> If we merge it to a guide ("coding style"), it could be summarized in fewer words. Basically explaining that key names need to be escaped with double quotes ("keyName") if there is another key with the same name somewhere in the same scope, otherwise it'll be considered as a reference and produce a CUE error.

Field shadowing is a complexe error that IMO deserve his own article to explain it, I think it's not enough to just explain this issue with a sentence

2022-06-09 01:18 UTC, samalba approved these changes

2022-06-09 01:18 UTC, merged