Sam improvements
dagger/dagger pull request #2890
Opened 2022-08-03 13:11 UTC by munichbughunter

This PR should improve the sam package for daggger. 

* Connect to tcp socket if you wanna build the sam image in a GitLab CI environment
* Improve code documentation
* Add README.md to give an overview how to use the package locally and also in a GitLab environment

2022-08-03 21:09 UTC, gerhard requested changes
This is a great PR with an amazing README, thank you @munichbughunter!

Apart from a few small changes for which I have left inline comments, there is a more significant change which would be greatly appreciated: could we move the content of the README.md into a doc page? I think it would go nicely under the **Use Cases** section, but **References** also works. WDYT @jpadams?

The Lint & DCO checks that are failing are self-explanatory. FWIW: https://docs.dagger.io/1227/contributing/#how-to-run-linters-locally

One important thing worth mentioning is that keeping `cue` snippets in separate files makes working with them easier. This is a good & recent example: https://raw.githubusercontent.com/dagger/dagger/v0.2.28/docs/core-concepts/1247-dagger-fs.md . I think that this will be helpful for those links: https://docs.dagger.io/1227/contributing#docs . This is also relevant: https://github.com/dagger/dagger/blob/main/docs/README.md .

Hope the above helps! This is not far off from getting merged.

2022-08-04 04:23 UTC, munichbughunter commented on pkg/universe.dagger.io/alpha/aws/sam/README.md
> +    "universe.dagger.io/x/munichbughunter@gmail.com/sam
You are right. Fixed.

2022-08-04 04:23 UTC, munichbughunter commented on pkg/universe.dagger.io/alpha/aws/sam/README.md
> +    "universe.dagger.io/x/munichbughunter@gmail.com/sam
You are right. Fixed.

2022-08-04 04:23 UTC, munichbughunter commented on pkg/universe.dagger.io/alpha/aws/sam/README.md
> +    "universe.dagger.io/x/munichbughunter@gmail.com/sam
Fixed.

2022-08-04 06:16 UTC, munichbughunter commented on pkg/universe.dagger.io/alpha/aws/sam/sam.cue
>  }
I get your point. When I take a look on the official
[Amazon Web Services Sam build image](https://hub.docker.com/r/amazon/aws-sam-cli-build-image-provided/tags) 

I only find one tag called latest.

2022-08-04 06:25 UTC, munichbughunter commented on pkg/universe.dagger.io/alpha/aws/sam/README.md
> +> :bulb: Check that [post](https://chris.beams.io/posts/git-commit/) to learn how write good commit message
I linked to the official contribution guide.

2022-08-04 11:09 UTC, gerhard commented on pkg/universe.dagger.io/alpha/aws/sam/sam.cue
>  }
In that case, I suggest that we link to the SHA256 instead. I can make the change, no worries.

2022-08-04 11:16 UTC, gerhard commented on pkg/universe.dagger.io/alpha/aws/sam/README.md
> +> :bulb: Check that [post](https://chris.beams.io/posts/git-commit/) to learn how write good commit message
That is a step in the right direction, for sure.

Let me move this README to docs and make the last change. I will wait for your sign-off before merging this.

2022-08-04 12:54 UTC, gerhard commented on pkg/universe.dagger.io/alpha/aws/sam/sam.cue
>  }
Resolved in https://github.com/dagger/dagger/pull/2890/commits/cc235cd05239ca8a2c295835c9d00a44e952cb52

2022-08-04 12:58 UTC, gerhard commented
@munichbughunter can you please double-check that everything looks right?

If it does to you, I can do another review and go for merge.

Almost there!

2022-08-04 15:00 UTC, gerhard approved these changes
These changes are ready to be merged from my perspective. We are just waiting on @munichbughunter to confirm that my last commits stayed true to the initial intent of this PR. When that happens, this is ready to **Squash and merge** (all checks should be green before we do that). If this doesn't happen today, I'm leaving it with you @grouville. Thanks!

2022-08-05 04:38 UTC, munichbughunter reviewed
@gerhard looks good for me - from my side it can be merged. 
Thank you for the support.

2022-08-07 23:51 UTC, merged