docs: add new layout to quickstart
dagger/dagger pull request #4537
Opened 2023-02-06 13:22 UTC by crjm

This will add a new layout to the Quickstart as previously thought on #4419.
The idea behind it is to improve the UX by allowing the user to scroll while maintaining the content and the editor in the same viewport.
Before making this change, we must modify every `.mdx` file in the quickstart, as the PoC is only implemented in the `quickstart-publish.mdx` file.

BTW took my time to ship this one as I wanted to maintain the current sidebar + avoid breaking the current structure of the `.mdx` files as having the ability of writing the docs in markdown is key.

Signed-off-by: Julián Cruciani <julian@dagger.io>

2023-02-06 13:25 UTC, crjm commented
Here's the [link with the new Layout](https://deploy-preview-4537--devel-docs-dagger-io.netlify.app/730264/quickstart-publish).

2023-02-06 13:48 UTC, crjm commented
Added layout to the [caching step](https://deploy-preview-4537--devel-docs-dagger-io.netlify.app/635927/quickstart-caching) to show how clicking a tab in the embed modifies the content too.

2023-02-07 09:52 UTC, slumbering commented on website/src/components/molecules/quickstartDoc.js
> +  useEffect(() => {
I guess this useEffect can be safely deleted. `isLoading` status is visible with the spinner line 24

2023-02-07 09:54 UTC, slumbering requested changes

2023-02-07 09:54 UTC, slumbering commented on website/src/components/molecules/quickstartDoc.js
> +                  {loading ? (
```suggestion
                  {loading && (
```

2023-02-07 09:54 UTC, slumbering commented on website/src/components/molecules/quickstartDoc.js
> +                  ) : null}
```suggestion
                  )}
```

2023-02-07 09:54 UTC, slumbering commented on website/src/components/molecules/quickstartDoc.js
> +                  {loading ? (
Did you try this instead of retuning null ?

2023-02-07 17:45 UTC, marcosnils commented
loved the new design! LGTM to migrate all the other quickstart pages.

2023-02-07 17:45 UTC, marcosnils approved these changes

2023-02-08 18:58 UTC, vikram-dagger commented
Looking good in general! I only have a couple of small comments for your further review:

- When viewed on mobile in landscape mode, it's quite hard to read the code and scroll because of the limited space. Does it make sense to keep the single column layout for mobile devices and only use the two column layout for larger screens?
- Also related to above, the column with the play button occupies a lot of space relative to the code window. Maybe we can scale the size of that button/column?
- Possible bug: When you click Play -> Login -> new login popup opens -> close the popup without actually logging in, the message in the embed says "You're authenticated".

2023-02-09 13:30 UTC, vikram-dagger commented
> I think we should have the embed available when the viewport is >1250px, and maybe also between 600px and 900px, before the sidebar reappears. WDYT?

I'm not really an expert on front-end UX so I'll defer to your judgement on this.

2023-02-09 21:25 UTC, crjm commented
I decided on showing the embed on the right in big screens only (>1200px), because the editor content wouldn't be readable enough otherwise. 
After adding the spinner to the `<iframe>` inside the content column, we'll be ready to start migrating the `.mdx` files.

2023-02-10 09:17 UTC, slumbering commented
@vikram-dagger @crjm regarding UX/UI question, you can also ask Camille.

2023-02-10 14:57 UTC, crjm commented
@slumbering 
Thanks for the review and sorry for not replying earlier. This was still a WIP and wasn't ready for review (the reviews that I asked for were to validate the layout mostly, instead of the implementation).

As for the UX review, thanks for your input @Camille-Elairin. :heart: 
This is the general idea: to have a terminal on the right that follows the user scroll. This allows reading the quickstart without loosing the position of the editor. 
The only problem I encountered was that medium screens <1200px would require, in a horizontal space, to render sidebar + content + editor, making the editor almost unreadable. This is why I decided to keep the editor floating on the right only when the screen is >1200px.

> (maybe displaying a small message saying there is an editor for bigger screen size?)

This is something similar to what Stripe has in the [quickstart we were benchmarking](https://stripe.com/docs/payments/quickstart?client=next). You can see that as you shrink horizontally, a warning appears.

> I was also wondering if you could display the editor in full width below the text

The editor will remain visible on smaller screens, but not on the right. It will be in the content column. You can see the current state [here](https://deploy-preview-4537--devel-docs-dagger-io.netlify.app/635927/quickstart-caching) (not all steps in the quickstart have that format yet).

2023-02-10 15:01 UTC, crjm commented
@Camille-Elairin LMK what you think and if it looks ok to you!
@vikram-dagger after confirmation from Camille, I'll start migrating the quickstart steps to the new format and make this PR ready for review.

2023-02-13 14:10 UTC, Camille-Elairin commented
@crjm seems good to me :)

2023-02-13 14:43 UTC, crjm commented
:wave:  @slumbering 
> The editor width seems to be very small (side effect ?)

This is because the only guides that have been migrated to the new Layout are `quickstart-caching.mdx` and `quickstart-publish.mdx`. Besides these two files, the rest should not render correctly.
Now that @Camille-Elairin gave the ok, I'll start migrating the new format to all the Quickstart files.

2023-02-13 18:18 UTC, crjm commented
@slumbering @vikram-dagger this is now ready for review.

2023-02-21 14:47 UTC, vikram-dagger approved these changes

2023-02-22 10:58 UTC, vikram-dagger commented
@crjm embed ids will change after https://github.com/dagger/dagger/pull/4632 is merged

2023-02-24 18:03 UTC, merged