docs: fix external link icons
dagger/dagger pull request #4788
Opened 2023-03-17 22:52 UTC by crjm

There's a current issue where the external links in the menu are not rendered correctly.
Docusaurus adds an SVG at the end of these links, but they have an absolute position. This makes the SVG appear at the top of the sidebar (after scrolling up), as it's shown here.

![image](https://user-images.githubusercontent.com/70334844/226065798-eb69e23f-99b5-4202-8a5e-701849e3fc92.png)

This PR also adds a chain icon next to the `Reference` link for the GraphQL reference for consistency with the remaining references.

2023-03-21 10:50 UTC, vikram-dagger commented
@crjm there is a file conflict

2023-03-21 14:40 UTC, crjm commented
@vikram-dagger conflict solved!

2023-03-22 07:43 UTC, vikram-dagger approved these changes

2023-03-22 07:44 UTC, vikram-dagger commented on website/sidebars.js
> +          label: "Reference 🔗",
I don't think this is needed. We use the chain icon to indicate an external resource (for Go and Python) but the API docs and the Node.js docs are hosted by us so do not require this icon IMO.

2023-03-22 07:45 UTC, vikram-dagger requested changes
Missed one item when approving, see comment.

2023-03-31 10:28 UTC, vikram-dagger approved these changes

2023-03-31 10:28 UTC, merged