fix: NodeSDK now compute nested array of objects.
dagger/dagger pull request #4800
Opened 2023-03-21 01:19 UTC by TomChv

Resolves: #4790

2023-03-22 19:44 UTC, marcosnils commented
LGTM initially @TomChv . Shall we add a test for it? The `api.spec.ts` file currently has tests for these kind of queries, so we should definitely validate this there.

2023-03-22 19:45 UTC, marcosnils requested changes
code LGTM. Let's add a test before merging :pray:

2023-03-23 02:32 UTC, marcosnils approved these changes

2023-03-23 02:32 UTC, sipsma approved these changes

2023-03-23 02:32 UTC, merged