docs: Highlight for better readability on code blocks
dagger/dagger pull request #4882
Opened 2023-04-01 21:38 UTC by 9spire

Fixes #4878 

Reference: https://docusaurus.io/docs/markdown-features/code-blocks#:~:text=You%20can%20set%20your%20own%20background%20color%20for%20highlighted%20code

2023-04-03 21:21 UTC, jpadams commented
@crjm I much prefer this highlighting, especially for large code block highlights. It was less of an issue for single lines, but looks good in single lines too.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/3187222/229630188-8d75ae0f-a749-48c3-a7b6-7cc064ee0c5f.png">

2023-04-03 21:35 UTC, jpadams commented
This color also good rbg(10, 36, 133)

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/3187222/229632862-995b02ef-7b14-44ce-aa1c-c8212bc0b1b9.png">

2023-04-03 22:24 UTC, crjm commented
First of all, thanks @9spire for the contribution!

I'm using [this codeblock](https://deploy-preview-4882--devel-docs-dagger-io.netlify.app/sdk/nodejs/783645/get-started#step-3-test-against-a-single-nodejs-version) to repro and the contrast is significantly better now.

> This color also good rbg(10, 36, 133)

IMO `rgba(32, 1, 111, 0.7);` pairs better in dark mode, but we can discern between dark and light modes when setting up variables, so setting `rgba(10, 36, 133, 0.8)` for the light mode and `rgba(32, 1, 111, 0.7)` for the dark mode seems like the perfect solution.

2023-04-03 22:26 UTC, crjm requested changes

2023-04-03 22:26 UTC, crjm commented on website/src/css/custom.scss
> +  --docusaurus-highlighted-code-line-bg: rgba(32, 1, 111, 0.7);
```suggestion
  --docusaurus-highlighted-code-line-bg: rgba(10, 36, 133, 0.8);
```

2023-04-04 22:02 UTC, jpadams approved these changes
LGTM! 🚀

2023-04-04 23:06 UTC, merged