fix: local cli doesn't expand tilda to home path in Go SDK
dagger/dagger pull request #5555
Opened 2023-08-02 08:45 UTC by wingyplus

I accidentally found when using local cli mode like this:

```
$ env _EXPERIMENTAL_DAGGER_CLI_BIN=~/src/github.com/dagger/dagger/bin/dagger go run ./ci build local-version
```

And it returns:

```
Error: exec: "~/src/github.com/dagger/dagger/bin/dagger": stat ~/src/github.com/dagger/dagger/bin/dagger: no such file or directory
Please visit https://dagger.io/help#go for troubleshooting guidance.
Usage:
  ci build [flags]

Flags:
      --dry-run        Build an image but do not publish image to the registry
  -x, --export-local   Export image into local docker engine
  -h, --help           help for build

exit status 1
```

I just recognize that `exec.LookupPath` would not resolve tilda (~) into `$HOME` directory. ><) This PR fix this issue.

2023-08-03 11:50 UTC, gerhard commented on sdk/go/internal/engineconn/cli.go
> +		binPath = strings.Replace(binPath, "~", os.Getenv("HOME"), 1)
I would use `user.Current().HomeDir` instead of `os.Getenv("HOME")` so that it works on all platforms, including Windows.

2023-08-03 11:51 UTC, gerhard requested changes
Nice find @wingyplus! I would suggest to make this Windows compatible (pretty sure `os.Getenv("HOME")` will not work).

Do we still have a Windows host to test this change on @helderco @grouville?

2023-08-03 12:06 UTC, wingyplus commented
@gerhard i think switch to use UserHomeDir would be better , it already handle windows home dir already https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/os/file.go;l=489. WDYT?

2023-08-03 13:48 UTC, helderco commented
> Do we still have a Windows host to test this change on @helderco @grouville?

Yeah, I do.

2023-08-03 13:54 UTC, helderco commented
> @gerhard i think switch to use UserHomeDir would be better , it already handle windows home dir already https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/os/file.go;l=489. WDYT?

We used to use this: https://github.com/mitchellh/go-homedir

2023-08-03 14:07 UTC, gerhard commented
If we can use a built-in package, I think that we should do that instead of introducing a new dependency.

2023-08-03 14:08 UTC, wingyplus commented
> > @gerhard i think switch to use UserHomeDir would be better , it already handle windows home dir already https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/os/file.go;l=489. WDYT?
> 
> We used to use this https://github.com/mitchellh/go-homedir in our codebase.

That’s great! We can use `Expand` to expand `~` to the home directory. :)

2023-08-03 14:08 UTC, gerhard commented
OK!

2023-08-03 16:54 UTC, wingyplus commented
Try it with powershell on Windows:

```
PS C:\Users\WingyMomo\src\github.com\wingyplus\dagger-sample> docker ps 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
PS C:\Users\WingyMomo\src\github.com\wingyplus\dagger-sample> $env:_EXPERIMENTAL_DAGGER_CLI_BIN = "~\src\github.com\dagger\dagger\bin\dagger.exe"
PS C:\Users\WingyMomo\src\github.com\wingyplus\dagger-sample> go mod edit -replace "dagger.io/dagger=C:\Users\WingyMomo\src\github.com\dagger\dagger\sdk\go"
PS C:\Users\WingyMomo\src\github.com\wingyplus\dagger-sample> go run .
Creating new Engine session... OK!
Establishing connection to Engine... OK!
3: resolve image config for docker.io/library/alpine:latest
3: > in from alpine
3: resolve image config for docker.io/library/alpine:latest DONE

5: pull docker.io/library/alpine:latest
5: > in from alpine
5: resolve docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1 
5: resolve docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1 [0.01s]
5: pull docker.io/library/alpine:latest DONE

5: pull docker.io/library/alpine:latest DONE
5: > in from alpine
5: pull docker.io/library/alpine:latest DONE

5: pull docker.io/library/alpine:latest
5: > in from alpine
5: pull docker.io/library/alpine:latest DONE
PS C:\Users\WingyMomo\src\github.com\wingyplus\dagger-sample> docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS         PORTS     NAMES
ee88885f1f0e   registry.dagger.io/engine:main   "dagger-entrypoint.s…"   7 seconds ago   Up 6 seconds             dagger-engine-0b3e1a47e49c9b77
```

2023-08-03 18:05 UTC, helderco commented
> If we can use a built-in package, I think that we should do that instead of introducing a new dependency.

It's an indirect dependency now (in go.mod). Used by a lot of packages.

2023-08-04 13:26 UTC, wingyplus commented
@helderco @gerhard switched to use go-homedir. Please kindly review. 🙇‍♂️

2023-08-09 18:57 UTC, gerhard approved these changes
👍 🚀

2023-08-09 18:57 UTC, merged

2023-08-09 19:01 UTC, gerhard commented
I forgot something before merging: `cd sdk/go && changie new`

Our contributing guide explains what it is & how to do it: https://github.com/dagger/dagger/blob/v0.8.1/CONTRIBUTING.md#3-add-release-notes-fragment. 

FWIW:
![image](https://github.com/dagger/dagger/assets/3342/d5cdea0b-e508-4648-be7f-74d4b93f8a3f)

I am going to open a follow-up PR to this that captures this in one command.