Add Instructions on how to get Dagger Engine to work on RHEL to the Docs
dagger/dagger pull request #6996
Opened 2024-04-02 19:04 UTC by levlaz

This adds a section the troubleshooting doc on how to get Dagger Engine to run on RHEL. Documents the issue that was fixed here: https://github.com/dagger/dagger/issues/6995

2024-04-03 14:56 UTC, vikram-dagger requested changes

2024-04-03 14:56 UTC, vikram-dagger commented on docs/current_docs/manuals/user/932727-troubleshooting.mdx
> +## Dagger Engine Restarts Due to `CNI setup error`
```suggestion
## Dagger restarts with a "CNI setup error"
```

2024-04-03 14:56 UTC, vikram-dagger commented on docs/current_docs/manuals/user/932727-troubleshooting.mdx
> +Dagger Engine requires the `iptable_nat` Linux Kernel Module in order to function properly. On some Linux Distributions (including RHEL 8.x and 9.x) this module is not loaded by default.
```suggestion
The Dagger Engine requires the `iptable_nat` Linux kernel module in order to function properly. On some Linux distributions (including Red Hat Enterprise Linux 8.x and 9.x), this module is not loaded by default.
```

2024-04-03 14:56 UTC, vikram-dagger commented on docs/current_docs/manuals/user/932727-troubleshooting.mdx
> +If you'd like to have this module loaded by default when your machine starts, then you can add it to the `/etc/modules-load.d/modules` file with the following command:
```suggestion
To have this module loaded automatically on startup, add it to the `/etc/modules-load.d/modules` file with the following command:
```

2024-04-03 17:13 UTC, vikram-dagger commented
Can you please also add the DCO so CI passes? Thanks.

2024-04-04 18:45 UTC, levlaz commented
> Can you please also add the DCO so CI passes? Thanks.

Yes, sorry just did that.

2024-04-04 18:47 UTC, levlaz commented
Thanks for the suggestions @vikram-dagger - I accepted them all, this is ready for review again.

2024-04-05 07:02 UTC, vikram-dagger approved these changes

2024-04-05 07:16 UTC, vikram-dagger commented
The Netlify failure is on account of the Netlify build timing out and not on account of any error in the PR. I have re-run the build manually on Netlify and it was green, so merging.

2024-04-05 07:16 UTC, merged