docs: Update Java integration page
dagger/dagger pull request #8209
Opened 2024-08-22 11:22 UTC by vikram-dagger

2024-08-30 19:38 UTC, jpadams requested changes
I think we need to highlight the two ways folks need to interact with Dagger x Java today.

- Writing client SDK style in Java
- Using the `Java` Dagger module with an SDK that supports Modules/Functions (not Java yet)

2024-08-30 19:38 UTC, jpadams commented on docs/current_docs/integrations/java.mdx
> +Dagger can be used to perform common CI tasks - testing, containerizing, publishing and more - for any Java application. This allows Java developers to create application delivery pipelines with the
Developers can use the Java SDK today to write a custom client (Cloak style), but Modules/Functions are not yet implemented. 

Additionally, the Java module we mention here is for use with module/function-able SDKs like TS, Go, Python and not Java today.

So there are two separate "integrations" today, not one. For this one:

```suggestion
Dagger can be used to perform common CI tasks - testing, containerizing, publishing and more - for any Java application in two ways. Java developers can create application delivery pipelines with the experimental Java SDK, using the same language and tooling they use for their Java applications, and benefitting from faster local runs by using Dagger to cache Maven dependencies. Note: The Java SDK is currently experimental and is moving soon to support Modules and Functions.

Additionally, if developers are using a Dagger SDK that supports Modules and Functions, such as the TypeScript, Python, or Go SDKs, they can leverage an excellent Java module from the [Daggerverse](https://daggerverse.dev/mod/github.com/jcsirot/daggerverse/java) which provides various Dagger Functions to work with Java projects. These Dagger Functions make it easy to configure the Java/Maven versions to use, the Maven sub-commands for building and packaging the application, and the output target.
```

2024-08-30 19:38 UTC, jpadams commented on docs/current_docs/integrations/java.mdx
> +The integration depends on the [`java` Dagger module](https://daggerverse.dev/mod/github.com/jcsirot/daggerverse/java), which provides various Dagger Functions to work with Java projects. These Dagge
```suggestion
The integration depends on the [`java` Dagger module](https://daggerverse.dev/mod/github.com/jcsirot/daggerverse/java) and is currently supported from SDKs that support Dagger Modules and Functions.
```

2024-09-04 18:59 UTC, vikram-dagger commented
> I think we need to highlight the two ways folks need to interact with Dagger x Java today.
> 
> * Writing client SDK style in Java
> * Using the `Java` Dagger module with an SDK that supports Modules/Functions (not Java yet)

I have modified your original suggestion taking into account @levlaz feedback in https://github.com/dagger/dagger/pull/8321. See https://github.com/dagger/dagger/pull/8321#issuecomment-2329766949. Lmk what you think!

2024-09-14 10:31 UTC, jpadams approved these changes
Ship it! 🚀

2024-09-14 14:00 UTC, merged