docs: add mention about dagger login on cloud-get-started documentation
dagger/dagger pull request #8693
Opened 2024-10-12 15:26 UTC by mcruzdev

## What?

This pull request aims to mention `dagger login` at [Dagger Cloud Introduction](https://docs.dagger.io/manuals/user/cloud-get-started/#connect-from-your-local-development-host) documentation.

## Why?

After the `dagger login` there was no mentions about `dagger login` on Dagger Cloud Introduction documentation.

The idea is to add it (`dagger login`) as a new way to connect to Dagger Cloud.

Closes #7734

2024-10-14 07:23 UTC, marcosnils commented
cc @vikram-dagger

2024-10-14 07:28 UTC, vikram-dagger commented on docs/current_docs/manuals/user/visualization/cloud-get-started.mdx
> +To configure for local development, run `dagger login` command.
```suggestion
To configure for local development, run the `dagger login` command.
```

2024-10-14 07:30 UTC, vikram-dagger commented on docs/current_docs/manuals/user/visualization/cloud-get-started.mdx
> +Browser opened to: https://auth.dagger.cloud/activate?user_code=FQNJ-BANG
```suggestion
Browser opened to: https://auth.dagger.cloud/activate?user_code=XXXX-YYYY
```

2024-10-14 07:30 UTC, vikram-dagger commented on docs/current_docs/manuals/user/visualization/cloud-get-started.mdx
> +Confirmation code: FQNJ-BANG
```suggestion
Confirmation code: XXXX-YYYY
```

2024-10-14 07:30 UTC, vikram-dagger requested changes
Thanks for this. See minor inline suggestions.

2024-10-15 06:38 UTC, vikram-dagger approved these changes

2024-10-15 06:38 UTC, merged