docs: add cli instructions to cache documentation
dagger/dagger pull request #9165
Opened 2024-12-11 01:15 UTC by cwlbraa

discussed in discord, these commands are otherwise undocumented and local-cache-prune can be useful for performance testing.

2024-12-11 10:31 UTC, vikram-dagger requested changes
Command looks fine, see note on tabs

2024-12-11 17:10 UTC, cwlbraa commented on docs/current_docs/configuration/cache.mdx
> +<TabItem value="CLI">
agreed, I was on the fence about the tabs as well.

2024-12-11 18:54 UTC, sipsma approved these changes

2024-12-12 04:32 UTC, vikram-dagger approved these changes

2024-12-12 04:32 UTC, merged