docs: add python poetry example for cache-volume
dagger/dagger pull request #9227
Opened 2024-12-16 09:04 UTC by clintonsteiner

* Add in poetry example utilizing caching from mage example in repo
* https://github.com/dagger/dagger/issues/5301

2025-01-06 11:10 UTC, vikram-dagger commented
Ping @helderco for review

2025-01-06 19:30 UTC, clintonsteiner commented
Believe the CI failures are incorrect, pinging @helderco for a review

2025-01-07 06:30 UTC, vikram-dagger commented
Re-running failed jobs in case it was a flake

2025-01-10 10:42 UTC, TomChv reviewed
I can approve once my comment is resolved, good job :)

2025-01-10 10:42 UTC, TomChv commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/poetry/main.py
> +            .with_mounted_cache("/root/.cache/poetry", dag.cache_volume("poetry_cache"))
I might be wrong because I lack of experience with poetry but [according to the doc](https://python-poetry.org/docs/configuration/#cache-dir), poetry default cache dir is `$HOME/.cache/pypoetry`.

```suggestion
            .with_mounted_cache("/root/.cache/pypoetry", dag.cache_volume("poetry_cache"))
```

Let me know what's the correct answer :D

2025-01-10 14:31 UTC, helderco commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
I'm not sure about this. There's more package managers around, including with the TypeScript SDK.

@vikram-dagger, would you rather go in and add more here (doesn't mean it has to be in this PR) or just have a single example for each SDK like today? I think it's ok to have examples for each package manager, just like you can have examples for running different kinds of applications, the main question is if this is the right place for it.

Something else to consider, even though in this cookbook entry the examples are language specific, usually these SDK tabs only change the syntax while keeping the pipeline itself the same. For example, you can have a go module that manages a poetry project too or vice versa.

My point is that the cookbook could either 1) provide one example to get an idea of how to cache dependencies, while you'd have somewhere else to look for the recommended way to do it with different package managers (this includes `apt` btw); 2) have the examples in different entries; 3) add them in this entry (where would you put `apt` though)?

2025-01-10 14:32 UTC, helderco commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/poetry/main.py
> +            .with_mounted_cache("/root/.cache/poetry", dag.cache_volume("poetry_cache"))
Yes, that's correct.

2025-01-10 14:57 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
Great point @helderco  and thanks for raising it!

I agree it would be useful to have examples for each of the common package managers. I'm OK with having them in a single entry (your suggestion #3) with comments, which might look something like this:

```
        return (
            dag.container()
            .from_("python:3.11")
            .with_directory("/src", source)
            .with_workdir("/src")
            # only if using pip
            .with_mounted_cache("/root/.cache/poetry", dag.cache_volume("poetry_cache"))
            # only if using poetry
            .with_mounted_cache("/root/.cache/pip", dag.cache_volume("pip_cache"))
...
```

We would need to also do this for the TypeScript example. I think the Go example would not need any changes?

You're right that we also need to consider `apt` which is currently not considered anywhere. Since `apt` is not a language-specific package manager, we could create a separate recipe/entry for it.

2025-01-13 15:20 UTC, clintonsteiner commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
Going to stay out of this one and let one of the two of you add in a seperate PR to minimize the scope of this one

2025-01-13 15:20 UTC, clintonsteiner commented
> I can approve once my comment is resolved, good job :)

Resolved related comment

2025-01-13 18:13 UTC, helderco commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
It's up to @vikram-dagger. There's a problem with the comments based approach though. It's not just the cache volume. Each package manager will have a different set of steps, like the commands to run, which can be more than one.

2025-01-20 06:13 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
Picking this back up...

I'm still in favour of having a single code snippet with comments, I think it will be easier to maintain and easier for a reader if it's all in one place. 

Considering what you said above @helderco , WDYT of the below? Does it make sense and would a Python developer easily understand how to use it for pip/poetry? Would it help to make the comments more verbose? 

If we can find a good approach for Python, then we could do the same for the TypeScript example in this same section.

```
        return (
            dag.container()
            .from_("python:3.11")
            .with_directory("/src", source)
            .with_workdir("/src")
             # only if using pip
            .with_mounted_cache("/root/.cache/pip", dag.cache_volume("pip_cache"))
            .with_exec(["pip", "install", "-r", "requirements.txt"])
            # only if using poetry
            .with_mounted_cache("/root/.cache/pypoetry", dag.cache_volume("poetry_cache"))
            .with_exec(
                [
                    "pip",
                    "install",
                    "--user",
                    "poetry==1.5.1",
                    "poetry-dynamic-versioning==0.23.0",
                ]
            )
            .with_exec(["poetry", "install", "--no-root"])
            .with_exec(["poetry", "install", "--only-root"])
        ) 
```

Note: there would be a separate example/recipe in the same section for `apt`.

2025-01-24 19:38 UTC, clintonsteiner commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
Does the naming actually matter here? Or would using poetry with pip_cache volume and .cache/pip work as long as you were consistent?

As a newcomer - I think I'd find it more helpful to explain the why here if that was the case
When I was first going through this - I took at face value that there must be some special naming going on with configurations for each package manager

Apologies if I"m missing something @vikram-dagger

2025-02-11 06:27 UTC, clintonsteiner commented
bump

2025-02-11 06:28 UTC, clintonsteiner commented
@helderco would you mind reviewing again witht he latest changes?

2025-02-12 13:06 UTC, helderco commented
> @helderco would you mind reviewing again witht he latest changes?

Sorry, @clintonsteiner! The code looks ok to me, I just defer to @vikram-dagger on the content organization part. So it's up to him.

2025-02-12 21:26 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
> Does the naming actually matter here? Or would using poetry with pip_cache volume and .cache/pip work as long as you were consistent?

The name of the cache volume shouldn't matter. Do poetry and pip both use the same `.cache/pip` directory?

2025-02-12 21:50 UTC, clintonsteiner commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
poetry uses ~/.cache/pypoetry

2025-02-12 21:50 UTC, clintonsteiner commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
can override with os variable POETRY_CACHE_DIR

2025-02-12 22:12 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
On further review, I think we shold stick with the existing pip-only example for https://docs.dagger.io/api/cache-volumes (since this page is intended to be illustrative not exhaustive), but include the additional poetry example to https://docs.dagger.io/cookbook#cache-application-dependencies.

Does that seem OK to you @clintonsteiner ?

If yes, should I push my proposed change to your branch so we can review?

2025-02-13 00:25 UTC, clintonsteiner commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
yep that works for me

2025-02-14 13:24 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
@clintonsteiner I haven't been able to work on this yet but just a note that I haven't forgotten :)

2025-02-21 15:15 UTC, vikram-dagger commented on docs/current_docs/api/cache-volumes.mdx
> +```python file=../cookbook/snippets/cache-dependencies/python/poetry/main.py
Modified now

2025-02-21 15:17 UTC, clintonsteiner commented on docs/current_docs/api/snippets/cache-volumes/python/main.py
> +            .with_mounted_cache("/root/.npm", dag.cache_volume("node-21"))
Think these were updated to npm and node by accident? @vikram-dagger

2025-02-21 20:06 UTC, vikram-dagger commented on docs/current_docs/api/snippets/cache-volumes/python/main.py
> +            .with_mounted_cache("/root/.npm", dag.cache_volume("node-21"))
No, that was deliberate. I updated the examples on https://docs.dagger.io/api/cache-volumes to be 1:1 equivalent - the previous version was actually inconsistent with other pages. we haven't adjusted language-specific features elsewhere. And I updated the examples on https://docs.dagger.io/cookbook to be language/package manager specific.

2025-03-09 14:57 UTC, vikram-dagger commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> +            .with_exec(["poetry", "install", "--only-root"])
@clintonsteiner can you please double-check this is correct ie. to run `poetry` twice?

2025-03-10 18:50 UTC, clintonsteiner commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> +            .with_exec(["poetry", "install", "--only-root"])
@vikram-dagger reviewed and this is for caching reasons and looks correct to me

2025-03-10 19:31 UTC, vikram-dagger commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> +            # No root first uses dependencies but not the project itself
This comment is duplicated. Is this intended @clintonsteiner ?

2025-03-18 07:41 UTC, vikram-dagger commented on docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> +            # No root first uses dependencies but not the project itself
@clintonsteiner please see above regarding duplicate comment

2025-03-20 10:35 UTC, vikram-dagger approved these changes

2025-03-20 10:36 UTC, vikram-dagger commented
@clintonsteiner there is a lint error on one of the code lines

```
/src/docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py:25:89: E501 Line too long (90 > 88)
   |
24 |             # if using poetry
25 |             .with_mounted_cache("/root/.cache/pypoetry", dag.cache_volume("poetry_cache"))
   |                                                                                         ^^ E501
26 |             .with_exec(
27 |                 [
   |
```

2025-03-20 10:37 UTC, vikram-dagger requested changes
Fix lint error

2025-03-20 10:54 UTC, vikram-dagger commented
Linter error, looking into it

```
--- /src/docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
1+++ /src/docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
@@ -16,11 +16,9 @@
             .from_("python:3.11")
             .with_directory("/src", source)
             .with_workdir("/src")
-
             # if using pip
             .with_mounted_cache("/root/.cache/pip", dag.cache_volume("pip_cache"))
             .with_exec(["pip", "install", "-r", "requirements.txt"])
-
             # if using poetry
             .with_mounted_cache(
                 "/root/.cache/pypoetry", dag.cache_volume("poetry_cache")

 file would be reformatted, 149 files already formatted
 ```

2025-03-20 10:55 UTC, clintonsteiner commented
> Linter error, looking into it
> 
> ```
> --- /src/docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> 1+++ /src/docs/current_docs/cookbook/snippets/cache-dependencies/python/main.py
> @@ -16,11 +16,9 @@
>              .from_("python:3.11")
>              .with_directory("/src", source)
>              .with_workdir("/src")
> -
>              # if using pip
>              .with_mounted_cache("/root/.cache/pip", dag.cache_volume("pip_cache"))
>              .with_exec(["pip", "install", "-r", "requirements.txt"])
> -
>              # if using poetry
>              .with_mounted_cache(
>                  "/root/.cache/pypoetry", dag.cache_volume("poetry_cache")
> 
>  file would be reformatted, 149 files already formatted
> ```

I put back for clarity - I'll let you remove those two lines
Thank you

2025-03-20 11:07 UTC, vikram-dagger approved these changes

2025-03-20 11:07 UTC, merged

2025-03-20 11:15 UTC, vikram-dagger commented
Thank you for the contributiong @clintonsteiner !